### ISSUE TITLE
Good stuff!

### ISSUE THREAD

**Issue by CareTiger** [JavascriptMick/nuxt3-boilerplate#5]
Interesting tech stack. Will you be making a Youtube video?

**Comment by JavascriptMick** [comment]
> Interesting tech stack. Will you be making a Youtube video?

Thanks for the feedback @CareTiger, yes I think I will do a video when I'm happy with a complete walkthrough of common scenarios.  Still a few things to do.

**Comment by JavascriptMick** [comment]
Video here. Yell out if you want to help with a deep dive tech video https://youtu.be/TkNTOlEsqmc

**Comment by CareTiger** [comment]
love it. thank you for sharing!
