### ISSUE TITLE
Slow response times

### ISSUE THREAD

**Issue by torstah** [JavascriptMick/nuxt3-boilerplate#6]
Hey. 

Thanks for creating this. 
Just curious if you also get crazy long response times for the deployed app? 

I get up to 6s just to fetch the notes here https://nuxt3-saas-boilerplate.netlify.app/dashboard

I'm located in Sweden, but still 6s?

**Comment by CareTiger** [comment]
i am not feeling it. based in arkansas. pretty fast.

**Comment by richard-edwards** [comment]
I'm near Toronto, Canada and it is pretty laggy. Getting the account info takes 1.5 sec and getting notes takes 3.5 sec. Slightly faster after a refresh but noticeable. Not sure if it's Supabase or Prisma but Prisma acts as a service layer between the client and Supabase.

**Comment by CareTiger** [comment]
most likely Prisma. I got rid of Prisma completely. This project is a nice starter but doesn't take into considerations like database migrations to Postgres. Prisma is a nightmare when it comes to migrations. I would get rid of that layer completely.

**Comment by CareTiger** [comment]
most likely Prisma. I got rid of Prisma completely. This project is a nice starter but doesn't take into considerations like database migrations to Postgres. Prisma is a nightmare when it comes to migrations. I would get rid of that layer completely.

**Comment by richard-edwards** [comment]
@CareTiger Yeah just getting into this template. I like it so far but I'm looking at something like Drizzle now after reading some things about Prisma. I've done raw SQL for ages so it shouldn't be a stretch to replace. Mainly looking for something strongly typed.

**Comment by CareTiger** [comment]
@richard-edwards i don't understand why you would need more type safety. i thought the whole purpose of the tRPC stack was to provide you with type safety during build. and 
`supabase gen types typescript --local tb`
already generates db types. so why the extra layer?

**Comment by richard-edwards** [comment]
You are probably correct. I'm still new to some of these concepts and looking at all of the options. Lot's of choices. Thanks for the note.

**Comment by torstah** [comment]
Wow thanks for all your comments. So maybe prisma is the culprit here, would also like to try to replace this with drizzle or similar. Any one got a fork to share? To create migrations manually is a nightmare....

Would love to have a solid Nuxt alternative to T3 app. But have not found anything great yet. I have tried: 

- https://github.com/sidebase
- https://create-v3-app.vercel.app/

and some other combos, but nothing is perfect yet. 

Appreciate any insights!

**Comment by johanguse** [comment]
Maybe Prisma's V5 may offer enhanced speed in this scenario. Have a look at the improvements the team has already made: https://www.prisma.io/blog/prisma-5-f66prwkjx72s

![image](https://github.com/JavascriptMick/nuxt3-boilerplate/assets/6184866/6d06b665-3499-44ec-bc1a-46c809805614)

**Comment by JavascriptMick** [comment]
Hi Guys, apologies for the tardy response.  Prisma was a conscious choice, I think it actually has a good migration story although to be fair, for this project, I haven't needed to do a migration and I didn't put any info in the Readme about it.  I'm also using the Prisma types through the entire application stack from the ORM layer through to the front end and this was also a deliberate choice. It means I can change the schema.prisma file and then the generated types automatically become available everywhere.  This allows me to move fast with new and altered features and really is a game changer.   I also haven't done a lot of performance tuning/checking and the demo site is running on free tier for everything I will try to add some performance checking and maybe tuning.  I will also check out Drizzle.  Thanks for your interest.

**Comment by JavascriptMick** [comment]
welp, it's not the database actually fetching notes.. this from the 'query performance' tab in supabase...

```
SELECT "public"."note"."id", "public"."note"."account_id", "public"."note"."note_text" FROM "public"."note" WHERE "public"."note"."account_id" = $1 OFFSET $2
```
Calls | Max Time | Mean Time | Min Time | Total Time
2506 | 0.60ms | 0.04ms | 0.01ms | 90.17ms

.. also under the 'slowest execution time', the worst performing query (one of the supabase admin queries) has a mean time of 190.74ms

**Comment by JavascriptMick** [comment]
thanks @johanguse, Prisma 5 seems to improve performance a lot on cold start.
