### ISSUE TITLE
stripe.webhooks.constructEvent works fine on local but causes issues after deploying on vercel

### ISSUE THREAD

**Issue by kamaalsultan** [JavascriptMick/nuxt3-boilerplate#7]
Hi everyone,
It works fine on local when I test using stripe-cli but it causes error after deploying on vercel
I get Error validating Webhook Event

**Comment by JavascriptMick** [comment]
Hi Mr Byte,

Sorry you are having this issue, I have zero experience deploying on Vercel as I have only been using Netlify.  If you are still having this issue, could you provide a little more information.

Michael

**Comment by kamaalsultan** [comment]
It is working fine now. I guess the error raised as my Vercel account was free plan. Now I upgraded and it is working fine.
