### ISSUE TITLE
Problem with consts

### ISSUE THREAD

**Issue by tommerty** [JavascriptMick/nuxt3-boilerplate#8]
Hi, just came across this and as someone who's trying to migrate from ExpressJS your boilerplate is very thought out! I've looked at many react/nextjs/astro templates but none seem to fit the bill like yours and I'm excited to learn some TS and Vue for that matter!

Question however: I've just spend about 40 minutes or so installing and getting everything set up, but I'm facing a lot of problems on the pricing page.

VSCode doesn't like copy/pasting errors so I've attached a screenshot of what I'm seeing below:

![image](https://github.com/JavascriptMick/nuxt3-boilerplate/assets/86270372/41d193dc-99f0-4285-b946-b712b5ca75c1)

My codebase is [here](https://github.com/tommerty/playing-with-nuxt) (using your template) if that's any help! I just wondering has something not worked as intended, or am I after doing some user error 😅 

Thanks again for your awesome boilerplate ❤️

**Comment by tommerty** [comment]
Sadly after further navigation I'm seeing problems on more than just the pricing page. On index for example I also see the same issues with `const user = useSupabaseUser()` `navigateTo` and on other pages giving errors about `useRuntimeConfig`, `useNotifyStore`, the list goes on and on.

**Comment by CareTiger** [comment]
getting a 404 on your link to the codebase

**Comment by tommerty** [comment]
> getting a 404 on your link to the codebase

Apologies, forgot it was a private repo (it's 4am lol)

Just made it public

**Comment by CareTiger** [comment]
did you follow the instructions in the README about the pricing page?

**Comment by tommerty** [comment]
Correct, I've added the IDs from Stripe and such, it seems to be a different problem than this.

For example, even unrelated pages are just having trouble with getting consts. I'll show a few screenshots here below to help drive home what I'm experiencing

![image](https://github.com/JavascriptMick/nuxt3-boilerplate/assets/86270372/dd91a99c-a442-490c-88df-257a140550e1)

![image](https://github.com/JavascriptMick/nuxt3-boilerplate/assets/86270372/22118bdc-7830-455c-96ba-2c290929c843)

![image](https://github.com/JavascriptMick/nuxt3-boilerplate/assets/86270372/00014be8-1006-431c-a3b3-3eeed82f88bb)

etc etc.

All leading to errors such as `cannot find x` or something like `Property 'activeMembership' does not exist on type '{}'.ts(2339)`

**Comment by CareTiger** [comment]
seems like a linting issue. did you try running the dev server?  i experience this all the time and running the dev server creates the .nuxt folder which clears out these issues

**Comment by tommerty** [comment]
I have, it's how I encountered there being a problem because my pricing values didn't change on the page. I've also tried installing via npm, yarn and pnpm all to no avail sadly.

I did notice when I run the build the "underlines" go away for a few seconds but then come back. I've honestly no idea what I'm doing wrong sadly

**Comment by CareTiger** [comment]
i am guessing you deleted the node_modules and package-lock and do re-install?

**Comment by richard-edwards** [comment]
What are you using for package manager? npm, yarn or pnpm?

I'm using pnpm and had to add a .npmrc file with this in it:

```
shamefully-hoist=true
auto-install-peers=true
```

**Comment by tommerty** [comment]
I've deleted my node_modules and package lock and done as you've suggested Richard and it has solved some of the issues, however some persist

![image](https://github.com/JavascriptMick/nuxt3-boilerplate/assets/86270372/87f93893-0849-4823-af9d-acf5a8691e6e)

Example from my pricing.vue page.

`Property 'x' does not exist on type {}`

**Comment by richard-edwards** [comment]
@tommerty Not sure what else to tell you. I just cloned your repo, added that .npmrc file I mentioned and did the ```pnpm install```, then ```pnpm dev``` and everything looks ok here.

If I remember correctly I did add supabase to the nuxt.config transpile section on my other machine but I didn't need to do it on this machine.

```
    transpile: ['trpc-nuxt','@supabase']
```

**Comment by tommerty** [comment]
Very strange! I've tried adding as you suggested in the nuxt.config but still the same. I'll try find some time during the week and just do a fresh install and start again and see what happens 🤞 thanks for giving me some of your time on this

**Comment by johanguse** [comment]
@tommerty try to update the typescript version on package-json to 5.1.6 and also update the tsconfig

```
{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "strict": true,
    "skipLibCheck": true,
    "ignoreDeprecations": "5.0",
    "suppressImplicitAnyIndexErrors": true,
    "types": [
      "@pinia/nuxt",
      "@nuxtjs/tailwindcss",
    ]
  }
}
```

**Comment by JavascriptMick** [comment]
Hi Tommy,

Thanks for your feedback.  Sorry you are having these issues. thanks @johanguse and @richard-edwards for following up and assisting.  I checked my local setup and not seeing these types of errors.  If there is however something I can change in the tsconfig to make the type linting/checking more robust, happy to look at it.  Even if there are some tips/steps that can be added to the README, that might help other folks happy to do that.  Yell out if you succeed/fail/learn something ;)

Michael

**Comment by JavascriptMick** [comment]
Closing this as it appears to be a localised issue.
